/* eslint-disable @next/next/no-script-component-in-head */
import Head from "next/head";
import Script from "next/script";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
// import "./path/OzLiveness.css";
// import  "./path/plugin_liveness.php";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {}, []);
  const handleCapture = () => {
    console.log("asdasdasldnaskjldskl");
    OzLiveness.open({
      lang: "en",
      action: ["photo_id_front", "photo_id_back", "video_selfie_blank"],
      overlay_options: { show_document_pattern: true },
      meta: { client_id: "john.doe", meta_key: "meta_value" },
      on_result: function (result: any) {
        console.log("on_result", result);
      },
      on_complete: function (result: { folder_id: string }) {
        console.log("on_complete", result);
        localStorage.setItem("folderId", result?.folder_id);
      },
      on_close: function () {
        console.log("on_close");
      },
      on_capture_complete: function (result: any) {
        console.log("on_capture_complete", result);
      },
      on_error: function (error: any) {
        console.log("on_error", error);
      },
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={() => handleCapture()}>Capture</button>
      </main>
    </>
  );
}
